### ISSUE TITLE
don't show correctly in Bottom Right

### ISSUE THREAD

**Issue by mohammadabushalhoob** [PriyamDutta/PDFloraButton#1]
hi 

my problem is the button don't show correctly in Bottom Right 
 the half of button only show, can you help pls .
code: 
let floraButton5 = FlorButton(withPosition: .bottomRight, size: 50.0, numberOfPetals: 3, images:["new-post-48","search_icon","profile_placeholder"]) 
thanks

**Comment by PriyamDutta** [comment]
Can you please provide screenshot ?

**Comment by PriyamDutta** [comment]
Closing issue as there is no response.
